-- REMOVE ANY DATABASE THAT ALREADY EXISTS --
DROP DATABASE IF EXISTS employee_tracker_db;

-- CREATE A NEW DATABASE --
CREATE DATABASE employee_tracker_db;

-- USE THE EMPLOYEE TRACKER DATABASE --
USE employee_tracker_db;

-- CREATE DEPARTMENT TABLE --
CREATE TABLE DEPARTMENT(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  NAME VARCHAR(100)
);

-- CREATE ROLES TABLE --
CREATE TABLE ROLES(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(100),
  SALARY INT,
  DEPT_ID INT NOT NULL,
  CONSTRAINT FK_department FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID) 
);

-- CREATE EMPLOYEES TABLES --
CREATE TABLE EMPLOYEES(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  ROLE_ID INT NOT NULL,
  MANAGER_ID INT,
  CONSTRAINT FK_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
  CONSTRAINT FK_manager FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
  -- The manager is an employee with a unique employee key. --
  -- We reference their employee key instead of having them in their own table - like a tree - no duplicate people --
);